### ISSUE TITLE
About the spectral loss for training the generator

### ISSUE THREAD

**Issue by ahmed-fau** [yanggeng1995/GAN-TTS#3]
Hi,
Thanks for sharing this nice implementation.

I can observe that you train the generator with a spectral (i.e. STFT-based) loss in addition to the adversarial one. While the original GAN-TTS paper trains the generator using only the adversarial one. 

Have you tried any ablation study to check whether training with the adversarial loss only could give reliable reconstructions?

Also regarding the conditioning features: it seems that you use the Mel spectrogram for conditioning. Did you try using discrete linguistic features (i.e. embeddings of textual data)? Otherwise, what is the major difference between this model and the MelGAN one?

Many thanks in advance
Ahmed

**Comment by yanggeng1995** [comment]
Hi
I have tried using just  adversarial loss. However, I did not get a better
result in 40w steps, such a result will have significant noise(maybe
because I didn't train enough ).

I have not apply off-diagonal orthogonal regularisation mentioned in the
paper, may be apply off-diagonal orthogonal regularisation is important.

At the same time, I also noticed that the batch size in the paper is very
large. I suspect that this piece will have a little impact on the results.

ahmed-fau <notifications@github.com> 于2019年11月20日周三 上午6:22写道：

**Comment by ahmed-fau** [comment]
And the Mel spectrogram is indeed used for conditioning the model, isn't it?

**Comment by yanggeng1995** [comment]
The Mel spectrogram  is just inputs. You can also use linguistic
features as inputs. When you use  Mel spectrogram as inputs， the model will
be treated as a vocoder, however, when you use  linguistic features as
inputs, the model will be treaded as a acoustic model.

ahmed-fau <notifications@github.com> 于2019年11月20日周三 下午4:10写道：

**Comment by ahmed-fau** [comment]
Thanks a lot!
